stockers=2
pickers=5
trolleys=10
tickSize=50
day=1
priorityEnabled=true
stockerBreakEnabled=false
#a stocker might take break at every 250 ticks on average
stockerBreakTickValue=250
#probablity of delivery each tick = 1/1000 TODO: change formula so that ticks are accepted
deliveryProbablity=0.01
# 100 pick attempts per day
pickAttemptyPerDay=100